### ISSUE TITLE
Document -use_hp_streams of mpi_overlap variant or enable it by default

### ISSUE THREAD

**Issue by Vetinar1** [NVIDIA/multi-gpu-programming-models#16]
The mpi_overlap variant has a -use_hp_streams flag that is not documented in the readme. I did not realize this and got some confusing results. I suggest either documenting this option or enabling it by default.

**Comment by jirikraus** [comment]
Thanks for pointing that out. Agree I missed to add documentation. In order to add the right documentation can you elaborate what you have been confused about?

**Comment by Vetinar1** [comment]
I first ran the variant without the flag (but using -nccheck 10) expecting it to use priority streams. Looking at the timeline view I got this result:

![Screenshot from 2022-04-13 17-03-01](https://user-images.githubusercontent.com/20323906/163210774-beb1e5e4-12c6-4568-9dfe-bb0078e1f960.png)

Which confused me because

- There is more downtime than I would expect in an overlap scenario
- Closer inspection revealed most Jacobi kernels were run on the same stream
- It appears that every second iteration, the kernels calculating the edges of the domain are calculated _after_ the main kernel, which then creates these gaps

All of which just seemed odd. Only when I looked at the code did I realize that you have to manually enable priority streams. When I run it with them enabled everything looks correct:

![c_mpi_overlap](https://user-images.githubusercontent.com/20323906/163211530-8397d383-5272-41ca-9cad-446b7ebc37db.png)

I don't know if the first variant is correct, but it didn't match my expectations.

edit: And to fix this, I think simply pointing out the -use_hp_streams flag in the readme file in either the list of variants or the run instructions would suffice

**Comment by jirikraus** [comment]
Thanks I see now what happens. If the norm is not checked in every iteration, except the first after a norm calculation, the kernels for the top boundary, the bottom boundary and the bulk compute are all launched while the GPU is busy computing the bulk from the from a previous iteration. So when the GPU is ready to start new work it can choose between those three and because there is no priority between the streams it can happen that the bulk kernel is started first although it was launched later. I tried to come up with something that fixes this in the code, but everything I could come up with would conflict with one of the teaching goals of this example. I would propose doing the following:
- Add  documentation for use_hp_streams to the README.md
- Add a warning if mpi_overlap is started with -nccheck > 1 and without -use_hp_streams: "Warning: when not calculating the norm in every iteration kernels might be executed in an order that breaks communication computation overlap. Also enable -use_hp_streams to avoid this issue."

Would that work for you?

**Comment by Vetinar1** [comment]
Yes, that would work.

**Comment by jirikraus** [comment]
Thanks again for the report. Issue is fixed with 974096830d2cf22675524e4a5cfdefb2dcd59d60. Closing this.
